### ISSUE TITLE
Idea: Reducing click count in searching for known types

### ISSUE THREAD

**Issue by eirannejad** [gtalarico/revitapidocs#112]
Let's say I want to find the documentation page for `FilteredElementCollector` class.

1. I open `revitapidocs.com` and type `FilteredElementCollector` in the search field.
2. Then I pick `FilteredElementCollector Class` from the drop down box
3. Then `revitapidocs.com` moves to documentation view but shows another popup window with match results for `FilteredElementCollector`
4. Then I need to click on the `FilteredElementCollector Class` again

The extra query popup box and click seems unnecessary, especially because sometimes the direct match is not listed at the top of the list and I need to scroll down in popup window to find it.

**Comment by gtalarico** [comment]
Yes, I agree (less clicks the better! : ) )

I see two possible scenarios when user picks from one of the Autocomplete suggestions:

| 1: User selects from one of the autocomplete suggestions:
| 2a: There are multiple results (search engine uses some "fuzzy matching" (ie `Wall Class`)
| 2b: There is only one result (ie. `FilteredElementCollector Class`)

One *2a*  even though there is one exact match, full list is displayed because user might be interested or looking for something else related to "Wall Class" (even though he picked from the autocomplete, I think he might want to see relevant results such as `WallType Class`, etc 
What it does happen howeever, is that search engine moves *exact_matches* to the top as shown below.

![image](https://user-images.githubusercontent.com/9513968/27996328-e72baa42-64ad-11e7-8128-cc1f8a1dfe86.png)


## Proposal
Use case 2a stays as is.
For 2b, instead of showing results with a single entry, user is redirected to the one entry.
Would that help improve this?

# Examples

## 2A

![image](https://user-images.githubusercontent.com/9513968/27996307-5c43f650-64ad-11e7-89aa-f4e01483f8b6.png)

## 2B
![image](https://user-images.githubusercontent.com/9513968/27996309-6365d5fc-64ad-11e7-8ded-7e62ef472f1e.png)

PS:
You mentioned: _"the direct match is not listed at the top of the list"_
Can you show an example? As shown above for case 2a, 100% matches should be moved up to the top

**Comment by eirannejad** [comment]
## Proposal
### 2C:
a. website does the fuzzy matching before showing the autocomplete results
b. user selects the desired entry
c. website goes directly to the result page (skipping the query popup)

At step (b) user can click a button (Expand) to expand the autocomplete results into a popup query that includes more information on each entry.

<img width="638" alt="screen shot 2017-07-09 at 11 09 31" src="https://user-images.githubusercontent.com/8197916/27996480-7e27aef8-6497-11e7-9249-51e892b4462d.png">

**Comment by gtalarico** [comment]
The autocomplete box is an out of the box solution by constructor.io  
It's customizable to some extend, but only for some of the settings available on its API.
Something like this would take some on-page JS hacking, so I would prefer to stay away from it for long term maintainability.

I think I have another possible solution, which might be even closer to the original intent of your suggestion:

### Case 1 - Search Query - Works currently
* 1a User Types "wall class"
* 1b Presses enter or clicks on search icon
* 1c Search results modal is displayed; exact matches is prioritized.

### Case 2 - Selecting from Autocomplete Suggestion > triggers auto redirect
(Closer to your original suggestion)
* 2a User Types "wall c"
* 2b User selects "Wall Class" from Autocomplete box by typing `down` + `enter` or clicking with mouse
* 2c User is redirected directly to page, skipping results modal.
By selecting from the autocomplete, we can infer the user has the intent of going to that exact entry vs searching for it.

## Implementation
I will have to give this some thought. The way constructor.io is currently implemented,  it's unaware of the relationship between a suggestion and its final url. See img below. With the current setup, search would still have to go through, results gathered, and only then redirected. This would not be efficient for the server nor a good user experience.

I will keep this in the backlog and try to implement next time I do some work on the website. I will have to revise the autocomplete uploader script to include item's URL, and then to some light work on the front end to auto-redirect.

Thanks for the suggestion, I think this would definitely be a better user experience.

![image](https://user-images.githubusercontent.com/9513968/27996579-0bd1829a-64b3-11e7-9cde-c7a11d34ef16.png)

**Comment by eirannejad** [comment]
Case 2 Case 2 Case 2 please 🥇 😄

**Comment by gtalarico** [comment]
Just thought of a small road block: some Autocomplete suggestions are not unique:
I think I know a way around it, but I just wanted to drop this in here for context later:

![image](https://user-images.githubusercontent.com/9513968/28182394-11c05896-67da-11e7-996d-66b7f45a8c0c.png)

![image](https://user-images.githubusercontent.com/9513968/28182397-14211378-67da-11e7-9cbd-26ae917e2ca6.png)

**Comment by gtalarico** [comment]
Fixed
https://github.com/gtalarico/revitapidocs/commit/855ab55d9f6ec513d59c24cc62aaf47870405ef0

![newautocomplete](https://user-images.githubusercontent.com/9513968/28749114-39d28c06-748b-11e7-8d77-2ad4f2edd59b.gif)

**Comment by gtalarico** [comment]
Ps: result modal is still there but only fires if search is submitted without an actively selected suggestion
