### ISSUE TITLE
Create Permalink / Human friendly url redirects for Resources

### ISSUE THREAD

**Issue by gtalarico** [gtalarico/revitapidocs#128]
[On behalf of @eirannejad]

Examples:
`revitapidocs.com?class=Autodesk.Revit.DB.FailureMessageAccessor`
or
`revitapidocs.com?latest=Autodesk.Revit.DB.FailureMessageAccessor`
or
`revitapidocs.com?link=Autodesk.Revit.DB.BuiltinCategory` 

The primary use case would be for using doc links in forums, code comments etc.
This would ensure the link is permanent regardless of Revit version.

Todo:
- [ ] Add API endpoint for resolving request and best year to redirect to.
- [ ] Add "Share" Button that creates these permalinks
- [ ] Resolve where to redirect  for ambiguous requests: Class? Method? Enums. Maybe add tag to url?
`revitapidocs.com?link=Autodesk.Revit.DB.Wall[Class]`
`revitapidocs.com?link=Autodesk.Revit.DB.Wall[Methods]`

**Comment by eirannejad** [comment]
There shouldn't be any ambiguous requests since you're including the full namespace.
Voting up your `link=` and suggesting this format for the permalinks:
``` ebnf
permalink = "revitapidocs.com?link=", symbol, { ".", symbol }, [ "->", doc_resource ];
```

`->` is just a suggestion. `[ ]` works just as well.

**Examples:**

Wall class:
`revitapidocs.com?link=Autodesk.Revit.DB.Wall`

Wall class, methods page:
`revitapidocs.com?link=Autodesk.Revit.DB.Wall->Methods`

SketchPlane class, properties page:
`revitapidocs.com?link=Autodesk.Revit.DB.SketchPlane->Properties`

Intersect method of PlanarFace class:
`revitapidocs.com?link=Autodesk.Revit.DB.PlanarFace.Intersect`

CanFlipFacing property of FamilyInstance class:
`revitapidocs.com?link=Autodesk.Revit.DB.FamilyInstance.CanFlipFacing `

Plane class, constructors page:
`revitapidocs.com?link=Autodesk.Revit.DB.Plane->Constructor`

Plane(XYZ, XYZ) constructor of method of Plane class:
`revitapidocs.com?link=Autodesk.Revit.DB.Plane.Plane(XYZ,XYZ)`

**Comment by gtalarico** [comment]
Only took one year 😊
