### ISSUE TITLE
Question : link to revitapidocs.com

### ISSUE THREAD

**Issue by PMoureu** [gtalarico/revitapidocs#97]
Hello
Don't worry, no bug ! 
I'm working on a tool to provide first aid documentation,
https://github.com/PMoureu/samples-Python-RPS/tree/master/RevitPythonHelper

The tool creates hyperlinks to perform a query on revitapidocs.com, are you ok with this principle ? 
Have you any suggestion about how the link is created ? i don't want to create bad traffic....

**Comment by gtalarico** [comment]
Great suff, Love the idea! 

I don't have any problems with you generating a link and including it in the addin
as long as it's not making requests directly to the server, 
as that could increase load on the server (+$ and performance)

If you can somehow extract the GUID from the members (not sure if possible), you could link directly to the page `revitapidocs.com/{year}/{GUID}.html`
Otherwise, the current api for search is
`revitapidocs.com/2015/?query=FilteredElementCollector` 
(no more #searchModal)

Not sure if it helps, but I have created a comprehensive JSON index with GUID as key, and Title, Description, parent member, and Namespaces here (minified!):
https://github.com/gtalarico/revitapidocs/blob/master/app/templates/json/db_index_min.json

**Comment by PMoureu** [comment]
I tried to find this GUID in first place, it's very well hidden :)
the search method was plan B, i will take a look at the JSON index, thanks a lot!

In fact i'm working on something bigger, including a treeview to navigate through modules/namespace/class (Python and .Net), with an extension manager to add helpful functions (bookmarks, notes, sharing..)
It's still sketchy and i want to convert all forms in WPF for better performance, but i'm facing some compatibility issues inside Revit.

The published module is a way for me to focus on the type analysis, then i will build the new whole version in wpf, something i can publish without compromising my whole career.

I was thinking about generating such indexes to provide autocompletion inside a filterbox without looping through big namespaces like RevitAPI or .Net Frameworks. 
This JSON index will definitely help me (as the rpw logger did).

**Comment by gtalarico** [comment]
Sounds awesome, happy to help!
Here is the un-minified version as well, much easier on the eye :)
https://www.dropbox.com/s/5n6dpu89zeccsyp/db_index.json?dl=0

**Comment by PMoureu** [comment]
Hello

i published my playground if you want to see the current result, maybe it can help you too !
https://github.com/PMoureu/iph

I left the links generation aside, for now, i think it needs some caching skills (even if i minimized the index 
with only title and memberof, it stays huuuge).

It's also possible to work on a link with RPW, to improve experience within Revit.

By the way, I stole your logger, do i need to mention your license more explicitely ?

**Comment by gtalarico** [comment]
Great, thanks for sharing, I will take a look when I get a chance. 
Mentioned for the logger  not required, but 
 credit to the project is always appreciated :)

**Comment by PMoureu** [comment]
Nice, many thanks !
